### ISSUE TITLE
The USB stack of ChibiOS may crash the firmware under certain circumstances

### ISSUE THREAD

**Issue by pavel-kirienko** [cvra/robot-software#105]
I hope you can tolerate my intrusion here, I'm just looking for friendly open source projects that leverage the ChibiOS's USB stack. The reason is that there appears to be a serious issue with the USB stack that may crash the OS under certain conditions; it is described here: http://www.chibios.com/forum/viewtopic.php?f=25&t=4568

So far the issue was observed on ChibiOS 16.1 running on STM32F105, STM32F373, and STM32F446. As can be seen in the linked thread, Giovanni is reluctant to take action until the issue is confirmed on newer revisions of the RTOS. Seeing as you're using version 17.6, perhaps you could spare half an hour to run a simple test described in the thread? That would be supremely useful for ChibiOS users in general.

Thanks!

**Comment by SyrianSpock** [comment]
Hi Pavel,
Sure we can try to reproduce the issue. However this week is busy for us. We'll have a look on Monday.

**Comment by pavel-kirienko** [comment]
The issue has been confirmed by Giovanni. Look out for updates!

**Comment by SyrianSpock** [comment]
Good to know, thanks :+1:
