### ISSUE TITLE
Make better use of the touchscreen

### ISSUE THREAD

**Issue by antoinealb** [cvra/robot-software#119]
The screens showed their potential for debug outputs when we used them as console. I think they can do much more, especially if we make use of their touch part. Then we could have real panels for things such as arm position, robot position, beacons, etc.

**Comment by Lu-ni** [comment]
We are almost done
to do: implement calibration of the touchscreen via the shell

**Comment by SyrianSpock** [comment]
we have a good setup for the screen, and already show score + position. All we need is to use it more :)
