### ISSUE TITLE
How can we handle time in GOAP?

### ISSUE THREAD

**Issue by antoinealb** [cvra/robot-software#127]
So as you all know, we had some issue to properly tell GOAP "Please do not do this action before XX seconds into the game". We tried hacking something, but it did not work somehow.

What I personally see would be to put the time constraint in the `can_run` method, where we would compare `trajectory_get_time() > 80` for example.

Another option would be to put the time in the state, but then I am afraid that GOAP would just do stupid actions "waiting" for the time to come instead of staying idle / trying new goals.

**Comment by nuft** [comment]
Also it might be good to not start an action if it can not complete before the end of the game.
Though this only works if we have fine grained actions so that we do a maximum of points while respecting the game's time limit.

**Comment by antoinealb** [comment]
I believe it would be a better fit to put this in the goal scheduling algorithm: pick the set of goals that can yield the most points in the remaining time or something like that.

**Comment by antoinealb** [comment]
>  pick the set of goals that can yield the most points in the remaining time or something like that

Also called the [0-1 knapsack problem](https://en.wikipedia.org/wiki/Knapsack_problem), which can be quite easily solved fortunately for us. The idea we discussed briefly tonight was:

* Have a set of all the goals in goap. Each goal produces an estimation of its payoff (score)
* For each goal, compute time it would take by calculating the GOAP path to solve them. Note that already solved goals will have a score of zero, that is fine.
* Pack all the goals in the remaining time using knapsack algorithm to yield best score.
* Process the selected goals in an order given by a manually specified priority.

**Comment by antoinealb** [comment]
For this year, we will stick to a simple approach where some tasks are forbidden to run after a given time and some tasks cannot run before a given time. Keeping the issue open for later.
