### ISSUE TITLE
Control proximity beacon in velocity mode

### ISSUE THREAD

**Issue by SyrianSpock** [cvra/robot-software#141]
Use motor encoder to control proximity beacon rotation in velocity mode. We should be able to ramp up the refresh rate from 4Hz currently to 10Hz

**Comment by antoinealb** [comment]
Why does the voltage mode prevent going to 10 Hz ?

**Comment by antoinealb** [comment]
Also I think this could be an okay task for somebody looking to get his feet wet with some lower level code, since we have some interest from the mechanical department to do software 🙊

**Comment by SyrianSpock** [comment]
So there were missing functionalities on the beacon's uavcan node:
- [ ] setpoint subscriber
- [ ] config loading from flash on boot

**Comment by SyrianSpock** [comment]
see #214
