### ISSUE TITLE
Localize an UWB tag in a 20x20m field

### ISSUE THREAD

**Issue by SyrianSpock** [cvra/robot-software#145]
We need to position a single moving UWB tag in a 20x20m field with a sub-meter accuracy. The end-goal is to position our rover on the minesweepers competition terrain made of 1m grid cells. 

MVP1:
- [x] Make ranging faster with single tag
- [x] Make sure EKF positioning works
- [x] Test in a 20x20m field

**Comment by antoinealb** [comment]
Isnt't completely done ? Or rather what is missing ?

**Comment by SyrianSpock** [comment]
Merged in #150
