### ISSUE TITLE
Generalize UWB positioning 

### ISSUE THREAD

**Issue by SyrianSpock** [cvra/robot-software#151]
We would like to position all robots on a table in real-time. This would gives us more information on the state of the table that we can use to enhance our game strategy. Currently, the positioning works and has been validated during the minesweepers competition in 2018. But it only works for multiple anchors and a single tag. We need to generalize it for 4 tags (2 for our robots and up to 2 opponent robots).

To be done:
* [ ] Get rid of hardcoded anchor mac addresses
* [ ] Implement TDMA to support 4 tags
* [ ] Test and validate positioning of 4 tags on the table

**Comment by antoinealb** [comment]
Won't fix as we will (should) have ARuCo.
