### ISSUE TITLE
Reimport motor board history

### ISSUE THREAD

**Issue by antoinealb** [cvra/robot-software#17]
as discussed tonight the motor firmware needs to be reimported to preserve history and allow for easy git logging / bisecting. @nuft are you volunteer for doing it ?

**Comment by nuft** [comment]
yes, I reimported it [here](https://github.com/cvra/robot-software/tree/import-history).

I couldn't reproduce the same history with the PR-merge. (there were merge issues if I tried to merge with `--no-ff`)

If you're ok with that, you can hard reset master onto it.

**Comment by antoinealb** [comment]
ok, done it.
