### ISSUE TITLE
Setup a wireless debug server

### ISSUE THREAD

**Issue by SyrianSpock** [cvra/robot-software#185]
To make testing on the table less painful, it would be nice to setup a wireless debug server (with a Raspberry Pi) to which we would wire:
- the STLink for firmware upload
- the CAN USB adapter to monitor CAN traffic
- the USB shell

**Comment by antoinealb** [comment]
some suggestions:

* power the raspi through the CAN bus
* use openocd GPIO adapter instead of st link, might work better?

**Comment by Lu-ni** [comment]
- [x] openocd GPIO for firmware upload
 - [x] the CAN USB adapter to monitor CAN traffic
 - [x] the USB shell
 - [ ] Bridge ethernet traffic on wlan (to have udp packet remotly)
 - [ ] Print a case and make the hardware cleaner

**Comment by antoinealb** [comment]
was useful to teach, wont finish as we got stuff to do.
