### ISSUE TITLE
UWB beacon firmware is built with exceptions enabled

### ISSUE THREAD

**Issue by nuft** [cvra/robot-software#191]
I noticed that for the uwb beacon all the exception handling code is linked with the firmware.

We should investigate and try to remove the cause as it blows up the binary size and makes debugging harder.

**Comment by antoinealb** [comment]
Could it be enough to add c++ stubs ? https://github.com/cvra/robot-software/blob/master/can-io-firmware/src/stubs.cpp

**Comment by nuft** [comment]
no, because Eigen calls `operator new()` which results in an error in `stubs.cpp`. 

I'm still investigating where the exceptions are coming from...

**Comment by antoinealb** [comment]
I think if you have `operator new()`, you will have exceptions brought in, as `new` might throw... Best to understand why Eigen is pulling dynamic memory allocation.

**Comment by nuft** [comment]
Apparently, it depends on the object size.
In the following example Eigen starts using malloc/new for n >= 8. (compiled for ARM)

```
    Eigen::Matrix<float, n, n> A;
    Eigen::Matrix<float, n, n> ATA = A.transpose() * A;
```

**Comment by nuft** [comment]
I'm surprised since I believed that basic operations in Eigen don't use malloc.
Turns out that's wrong 😕

**Comment by antoinealb** [comment]
Disappointing... But I think there are some ways to prevent Eigen from using malloc()

**Comment by antoinealb** [comment]
Apparently its possible to do it using `Eigen::Map` instead. Pinging resident Eigen expert @SyrianSpock 

https://stackoverflow.com/questions/21402426/c-eigen-matrix-operations-vs-memory-allocation-performance

**Comment by SyrianSpock** [comment]
If we start doing memory allocation ourselves to avoid Eigen using malloc, the code is gonna get very ugly. Eigen is using malloc for temporaries, one way to reduce them is to use the `noalias()` method (http://eigen.tuxfamily.org/dox/TopicWritingEfficientProductExpression.html). 

I prefer to study the problem more, using `EIGEN_NO_MALLOC` to trigger assert failures on malloc calls, we can use that to understand what's happening. One way to tweak allocation would be implementing our own allocator to replace `aligned_malloc` implementation in Eigen (https://github.com/cvra/eigen/blob/9e97af7de76716c99abdbfd4a4acb182ef098808/Eigen/src/Core/util/Memory.h#L150-L171)

**Comment by nuft** [comment]
I checked agian, actually `operator new()` is not called. (I think because our matrix dimensions are small enough)

However, I found that overwriting `std::__throw_bad_function_call()` removes the exception handling code.
