### ISSUE TITLE
Robot specific parameters storage and loading

### ISSUE THREAD

**Issue by SyrianSpock** [cvra/robot-software#23]
We need to choose how to store and load the configuration of different robots. Do we use `config.yaml` for everything and remove all the defines.
There are common parameters and ones that are specific to each robot. How do we separate those ?

**Comment by antoinealb** [comment]
Do you have an example for common parameters ?

I would put everything in config.yaml but keep default values define'd. I think we could separate in 3 files:

* config_common.yml
* config_debra.yml
* config_small_robot.yml

We will always load parameters from the common file. Then we will load the robot specific one.

**Comment by SyrianSpock** [comment]
> Do you have an example for common parameters ?

All calibrated parameters (wheelbase, encoder pulses per mm, etc)

**Comment by antoinealb** [comment]
Aren't those ones the perfect examples of per-robot parameters ?

**Comment by SyrianSpock** [comment]
Completely misread the question :|
Common parameters are all non-calibrated parameters (motor wheel radius, motor track length), map / strategy specific stuff (opponent obstacle size)

**Comment by antoinealb** [comment]
ok makes more sense !

2016-12-21 15:31 GMT+01:00 Salah-Eddine Missri <notifications@github.com>:

**Comment by SyrianSpock** [comment]
For now, we'll keep one config file for each robot.
