### ISSUE TITLE
Check that lwIP is still working on master firmware

### ISSUE THREAD

**Issue by antoinealb** [cvra/robot-software#241]
* ping 
* encoders should be broadcast via UDP

**Comment by antoinealb** [comment]
Still to be done; it appears the master-firmware is crashing on boot when not connected to a real robot peripherals.

**Comment by nuft** [comment]
* ping is working.
* no topics are broadcast.

I had to comment out GUI and PWM init routines.
Debug UART over ST-Link doesn't work (wrong serial device).

**Comment by nuft** [comment]
I forgot to re-enable the right parts.
UDP topic streaming is working.
