### ISSUE TITLE
Memory allocation problems

### ISSUE THREAD

**Issue by SyrianSpock** [cvra/robot-software#25]
A memory related problem appeared recently when I tried to add support for additional motors on the bus (to support all motors in Debra's arms). This issue was not related to a specific motor but rather to the number of motor drivers used.

With the help of @Stapelzeiger @nuft, we successfully identified the issue [in the motor driver](https://github.com/cvra/robot-software/blob/d76c6cd8c23c0b6c83da06156da24a6ea016a52c/master-firmware/src/can/motor_driver_uavcan.cpp#L78) where `new` failed because of lack of memory. A temporary fix is to free some place on the heap by reducing the size of trajectory buffers (from last year).

Long term solution:
- Remove trajectory buffers as we don't use them anymore (they were meant for using the master board as IP-CAN relay)
- Move thread stacks to CCM
- Reduce obstacle avoidance internal buffer to accommodante enough obstacles for the competition, but not too much.

**Comment by antoinealb** [comment]
(Partially) solved by #37.
