### ISSUE TITLE
Unit tests fail on Clang

### ISSUE THREAD

**Issue by antoinealb** [cvra/robot-software#52]
For some reason Travis version of clang has a broken c++ library. I disabled Clang's build in ae47b7c but it would be good to re enable it later.

Possibly relevant links:

* https://github.com/philsquared/Catch/issues/334
* https://github.com/Andersbakken/rtags/issues/204

**Comment by antoinealb** [comment]
Builds on my laptop with Clang trunk but some tests fail. Would be really nice to have it working in CI.

**Comment by antoinealb** [comment]
We could even enable [AdressSanitizer](https://github.com/google/sanitizers/wiki/AddressSanitizer) to hunt for memory being used before init. I think something similar exists for GCC (`-fsanitize=address`).

**Comment by SyrianSpock** [comment]
I would be keen on activating all the sanitizers https://clang.llvm.org/docs/SanitizerSpecialCaseList.html

**Comment by SyrianSpock** [comment]
Fixed by #133
