### ISSUE TITLE
position_manager is not properly synchronized

### ISSUE THREAD

**Issue by antoinealb** [cvra/robot-software#7]
We should add some locks around all operations manipulating positions. I personally believe it should not go in the module source code itself, but rather around every caller site.

**Comment by SyrianSpock** [comment]
I was thinking about that. And you are right, Aversive should remain platform agnostic, so no locks inside its functions.
Same applies for:
- the trajectory manager, we need the main thread to be defined differently
- the calls to chThdSleep etc, we should about refactoring that

**Comment by antoinealb** [comment]
wont fix; obsolete
