### ISSUE TITLE
CAN-IO support for ramp PWM output to protect servo

### ISSUE THREAD

**Issue by nuft** [cvra/robot-software#74]

**Comment by antoinealb** [comment]
Basic idea of how it would work:

* The UAVCAN message (`20131.ServoPWM.uavcan`) would be extended with a speed & acceleration variable.
* The quadramp module will be used for ramp generation.
* As we don't have enough RAM for additional stack, it will probably run from the UAVCAN thread, using an UAVCAN timer.

Does this work for you guys ?

**Comment by SyrianSpock** [comment]
Sounds good, it can still be wrapped in a separate module (that depends on quadramp) and exposes a simple interface that's used inthe UAVCAN thread. Could also be used on the master board.
